spring.application.name=newspaper

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

news.api.key=${NEWS_API_KEY}
news.api.url=https://gnews.io/api/v4/top-headlines

jwt.secret=${JWT_SECRET}

server.port=${PORT:8080}